### ISSUE TITLE
This template doesn't have the documentation tools

### ISSUE THREAD

**Issue by ionelmc** [webcomponents/polymer-boilerplate#20]
But https://github.com/PolymerLabs/seed-element does. Why are they so different?

**Comment by zenorocha** [comment]
The reason is because this template is compatible with [xtag-boilerplate](https://github.com/webcomponents/xtag-boilerplate), [element-boilerplate](https://github.com/webcomponents/element-boilerplate), which are all the same templates for [generator-element](https://github.com/webcomponents/generator-element). A good documentation tool is one that could leverage all those different solutions.
